# Generated by Django 6.0.5 on 2026-06-04 20:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('accent', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('age_range', models.CharField(blank=True, max_length=100)),
                ('speaking_style', models.CharField(blank=True, max_length=255)),
                ('emotion_notes', models.TextField(blank=True)),
                ('voice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='voices.voice')),
            ],
            options={
                'db_table': 'voice_profiles',
            },
        ),
    ]
