# Generated by Django 6.0.5 on 2026-06-04 20:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('voices', '0002_voiceprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sample_type', models.CharField(choices=[('training', 'Training'), ('reference', 'Reference'), ('emotion', 'Emotion'), ('conversation', 'Conversation'), ('narration', 'Narration')], max_length=50)),
                ('weight', models.FloatField(default=1.0)),
                ('is_primary', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_samples', to='assets.asset')),
                ('voice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='voices.voice')),
            ],
            options={
                'db_table': 'voice_samples',
            },
        ),
    ]
