# Generated by Django 6.0.5 on 2026-06-05 21:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0004_charactervoiceassignment'),
        ('stories', '0005_scenecharacter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wardrobe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobes', to='characters.character')),
            ],
            options={
                'db_table': 'wardrobes',
            },
        ),
        migrations.CreateModel(
            name='SceneWardrobeAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe_assignments', to='stories.scene')),
                ('wardrobe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobes.wardrobe')),
            ],
            options={
                'db_table': 'scene_wardrobe_assignments',
            },
        ),
        migrations.CreateModel(
            name='WardrobeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('item_type', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('wardrobe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wardrobes.wardrobe')),
            ],
            options={
                'db_table': 'wardrobe_items',
            },
        ),
    ]
