# Generated by Django 6.0.5 on 2026-06-04 20:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('scene_number', models.PositiveIntegerField()),
                ('summary', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('time_of_day', models.CharField(blank=True, max_length=100)),
                ('duration_estimate', models.PositiveIntegerField(default=0, help_text='Estimated duration in seconds')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='stories.story')),
            ],
            options={
                'db_table': 'scenes',
                'ordering': ['scene_number'],
                'unique_together': {('story', 'scene_number')},
            },
        ),
    ]
