# Generated by Django 6.0.5 on 2026-06-04 20:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_scene'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('shot_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('camera_type', models.CharField(blank=True, max_length=100)),
                ('camera_movement', models.CharField(blank=True, max_length=100)),
                ('duration_seconds', models.PositiveIntegerField(default=5)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='stories.scene')),
            ],
            options={
                'db_table': 'shots',
                'ordering': ['shot_number'],
                'unique_together': {('scene', 'shot_number')},
            },
        ),
    ]
