# Generated by Django 6.0.5 on 2026-06-04 20:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('stories', '0003_shot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storyboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storyboards', to='assets.asset')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storyboards', to='stories.scene')),
            ],
            options={
                'db_table': 'storyboards',
            },
        ),
    ]
