# Generated by Django 6.0.5 on 2026-06-05 16:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_characterreference'),
        ('stories', '0004_storyboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneCharacter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role_name', models.CharField(blank=True, max_length=100)),
                ('is_speaking', models.BooleanField(default=False)),
                ('importance', models.PositiveSmallIntegerField(default=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_scenes', to='characters.character')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_characters', to='stories.scene')),
            ],
            options={
                'db_table': 'scene_characters',
                'unique_together': {('scene', 'character')},
            },
        ),
    ]
