# Generated by Django 6.0.5 on 2026-06-04 19:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('age_range', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('height', models.CharField(blank=True, max_length=50)),
                ('body_type', models.CharField(blank=True, max_length=100)),
                ('skin_tone', models.CharField(blank=True, max_length=100)),
                ('eye_color', models.CharField(blank=True, max_length=100)),
                ('hair_color', models.CharField(blank=True, max_length=100)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('personality_notes', models.TextField(blank=True)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='characters.character')),
            ],
            options={
                'db_table': 'character_profiles',
            },
        ),
    ]
