# Generated by Django 6.0.5 on 2026-06-04 19:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('characters', '0002_characterprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reference_type', models.CharField(choices=[('face', 'Face'), ('body', 'Body'), ('full_body', 'Full Body'), ('clothing', 'Clothing'), ('expression', 'Expression'), ('pose', 'Pose')], max_length=50)),
                ('weight', models.FloatField(default=1.0)),
                ('is_primary', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_references', to='assets.asset')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='characters.character')),
            ],
            options={
                'db_table': 'character_references',
            },
        ),
    ]
