# Generated by Django 6.0.5 on 2026-06-05 19:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_characterreference'),
        ('voices', '0003_voicesample'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterVoiceAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_assignment', to='characters.character')),
                ('voice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_characters', to='voices.voice')),
            ],
            options={
                'db_table': 'character_voice_assignments',
            },
        ),
    ]
